name: Daily Kimi

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,6,12,18 * * *"
jobs:
  run-my-job:
    name: Post Picture
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install packages
        run: bun i
      - name: Run program
        run: bun run index.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          OAUTH_SECRET: ${{ secrets.OAUTH_SECRET }}
      - name: Commit and Push Data
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
